apiVersion: v1
kind: Service
metadata:
  name: service-demo
  labels:
    app: service-demo
spec:
  selector:
    app: nginx-demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
