version: '3'

services:
  redis:
    image: redis:latest
    container_name: REDIS
    ports:
      - 6378:6379
    expose:
      - 6378
    networks:
      - redis-network
    command: redis-server --appendonly yes
networks:
  redis-network:
    driver: bridge
