apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  labels:
    app: pod-configmap
spec:
  containers:
    - name: busybox
      imagePullPolicy: Always
      image: busybox
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: configmap-demo
      env:
        - name: mysql
          valueFrom:
            configMapKeyRef:
              key: mysql
              name: config-demo
        - name: port
          valueFrom:
            secretKeyRef:
              key: port
              name: secret-demo
  volumes:
    - name: cofigmap
      projected:
        sources:
          - configMap:
              name: user.example.color
          - configMap:
              name: user.example.hello