apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    app: pod-demo
spec:
  nodeSelector:
    disktype: ssd
  hostAliases:
    - ip: "10.1.2.3"
      hostnames:
        - k8s.example
        - kubernetes.example
  hostNetwork: true
  hostIPC: true
  hostPID: true
  shareProcessNamespace: true
  tolerations:
    - key: "nod"
      value: "nod"
      operator: "Equal"
      effect: "NoSchedule"
  containers:
    - name: podcontainer
      image: busybox
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /data
          name: podvolume
          readOnly: true
      ports:
        - containerPort: 80
          hostPort: 8080
      lifecycle:
        postStart:
          exec:
            command:
              - echo
              - "hello"
        preStop:
          exec:
            command:
              - echo
              - "end"
  volumes:
    - name: example
      hostPath:
        path: /etc/logs
