version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "cluster.name=es-cluster-name"
      - "node.name=es_01"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=admin123"
    networks:
      - esnetwork
networks:
  esnetwork:
    driver: bridge
