apiVersion: v1
kind: Pod
metadata:
  name: go-anything-pod
spec:
  containers:
    - name: go-anything-pod-container-0
      image: swr.cn-north-1.myhuaweicloud.com/go-test/go-anything:v0.6
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "0.5"
          memory: "400Mi"
        requests:
          cpu: "0.4"
          memory: "300Mi"
      lifecycle:
        postStart:
          exec:
            command: ["/bin/bash", "-c", "echo Hello go-anything!!!"]
        preStop:
          exec:
            command: ["/bin/bash", "-c", "echo try to delete pod!!!"]
      livenessProbe:
        exec:
          command:
            - echo
            - "hello"
        periodSeconds: 5
        initialDelaySeconds: 5
